### ISSUE TITLE
relations return null on POST but not on GET

### ISSUE THREAD

**Issue by wlawt** [MLH-Fellowship/babel-sandbox-server#7]
Found from #6 - to reproduce follow similar steps in that PR

**Possible problem:**
`Source` `Plugin` are association fields that are set up only when the action is complete. The other fields that are not associations like `created` `id` return its expected output.

**On POST:**
![image](https://user-images.githubusercontent.com/22751307/89056103-79466d80-d329-11ea-86e0-a92bd7f48c30.png)

**On GET:**
![image](https://user-images.githubusercontent.com/22751307/89056129-86fbf300-d329-11ea-9b6c-ddc24dfc24b0.png)

**Comment by mohammedsahl** [comment]
Note: problem persists for `POST /api/v1/blobs/fork/:id` in #15

**Comment by wlawt** [comment]
@mohammedsahl running #15 I no longer see `source` and `plugin` to be `null`

![image](https://user-images.githubusercontent.com/22751307/89792706-eeb4f980-daf2-11ea-818f-3a5ff96adb40.png)

**Comment by mohammedsahl** [comment]
> @mohammedsahl running #15 I no longer see `source` and `plugin` to be `null`
> 
> ![image](https://user-images.githubusercontent.com/22751307/89792706-eeb4f980-daf2-11ea-818f-3a5ff96adb40.png)

That's because of this cheeky [line](https://github.com/MLH-Fellowship/babel-sandbox-server/pull/15/files#diff-9911365c616aa8cb05f94d9b43e62b38R61) 😄
